name: Continuous Integration
on:
  workflow_dispatch:
  #  pull_request:
  push:
    branches: [ ]

jobs:
  test-action:
    name: GitHub Actions Test
    env:

      FCLI_EXECUTABLE_LOCATION: "."

    #    container:
    #      image: fortifydocker/fortify-ci-tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1
        with:
          version: 23.1.0
          client-auth-token: ${{ secrets.FTFY_SAST_CLIENT_TOKEN }}

      - name: Download CLIs
        run: |
          wget -qO- https://github.com/fortify/fcli/releases/download/v1.3.2/fcli-linux.tgz | tar zxf -  

      # GitHub Action for Application Version creation
      - name: Create Application Version
        uses: agendry-pub/gha-ssc-create-application-version@v1
        with:
          ssc_base_url: ${{ vars.FTFY_SSC_BASE_URL}}
          ssc_ci_token: ZDQ4NWY0MDYtYzY4OS00YjE2LWIxYjUtOTVkOWE2NzYzZTM1
          ssc_app: PetClinic
          ssc_version: 1.1-gl-ast
          #          ssc_ci_username: ${{ secrets.FTFY_CI_USERNAME }}
          #          ssc_ci_password:  ${{ secrets.FTFY_CI_PASSWORD }}
          ssc_version_attributes: |
            Accessibility=Internal Network Access Required
            DevStrategy=Internally Developed
            DevPhase=New

      - name: Test Local Action
        #        if: always()
        id: test-action
        uses: ./
        env:
          FCLI_DEFAULT_TOKEN_EXPIRE: "1h"

        with:
          ssc_base_url: ${{ vars.FTFY_SSC_BASE_URL}}
          ssc_app: PetClinic
          ssc_version: 1.1-gl-ast
          ssc_ci_token: ${{ secrets.FTFY_CI_TOKEN_ENC }}
          #          ssc_ci_username: ${{ secrets.FTFY_CI_USERNAME }}
          #          ssc_ci_password:  ${{ secrets.FTFY_CI_PASSWORD }}
          sast_scan: false
          sast_client_auth_token: ${{ secrets.FTFY_SAST_CLIENT_TOKEN }}
          sast_build_options: "-bt none"
          security_gate_action: warn
          security_gate_filterset: Critical & High
          summary_filterset: Critical & High


#  test-action-local:
#    name: GitHub Actions Test but local
#
#    runs-on: fortify-ubuntu
#    steps:
#      - name: Checkout
#        id: checkout
#        uses: actions/checkout@v4

#      - name: Test Local Action
#        if: always()
#        id: test-action
#        uses: ./
#        env:
#          FCLI_DEFAULT_TOKEN_EXPIRE: "1h"
#          FCLI_EXECUTABLE_LOCATION: "/fortify/fcli/"
#          FCLI_DISABLE_SSL_CHECKS: true
#        with:
#          ssc_base_url: "https://fortify.local"
#          ssc_app: "github_action_dev_app"
#          ssc_version: "${{ github.run_id }}"
#          ssc_ci_username: ci.user
#          ssc_ci_password: One4All@1234
#          ssc_version_attributes: |
#            Accessibility=Internal Network Access Required
#            DevStrategy=Internally Developed
#            DevPhase=New
#            Languages=C,C++,Java
#            Interfaces=Programmatic API,Web Access
#          ssc_version_issue_template: PCI v4.0 Basic Issue Template
